### PR TITLE
New feature/sitemap files for book detail pages/490

### LINKED ISSUE #490: Write python script to create sitemap files for book detail pages
@joshuago78 the implementation spec is based on conversations w/ @alyxrossetti and research. It should be pretty simple, as basically it's just creating `.txt` files. 

The bulk of our sitemap is the item detail page URL's, and I believe the rest of it can be done by hand for now as it is mainly help/FAQ pages.

Down the line, the thing which will effect SEO the most I think is the `lastmod` property. We can use this to indicate to crawlers when we have new/changed records.

We should also set the `priority` of record URL's to be higher than other pages - 0.8 (scale of 0 to 1) is a value I have seen in many examples. And maybe set, say, the 'Feedback' page to have priority `0.3`.

The `changefreq` prop does not seem as critical for us right now. 

------------

Write a python script to generate sitemap files with URL's for individual book detail pages. We will then run this script every time we have new or changed records to index in Elasticsearch. Eventually it can be connected to a database and/or our ingest pipeline. For now it can be simple. 

http://www.sitemaps.org/protocol.html
- Sitemaps can include links to other sitemap files. We should have a 'master' sitemap index `.xml` file which includes links to sitemap files for the individual record URL's. 
  - Each file must have no more than 50,000 URL's and be less than 10MB
  - Each file can be in `.xml` or `.txt` format. I recommend, for now, `.txt` format, which is simply a list of URL's - one per line. 
- The python script can either get `_grp_id` and `ingest_date` values from the database @alyxrossetti is working on, or from reading the batch record files which are prepared for indexing into Elasticsearch.
  - The script should never allow a `lastmod` date (say, from a bad `ingest_date` val)  <  current date (date script is ran).
- The script should output `.txt` files following the format specified above to the desired directory.
- The script should update the sitemap index file(master file) to include links to each 'child' sitemap file. See link above for specs on this.
  - The script should set `lastmod` and `priority` properties in the site index file associated with each 'child' file (**note:** this is nice but not critical for launch -- we can always set `lastmod` manually for going live and update later). 
- The python script should be written so that it will be easy to modify to receive data via a file or from a database, and so that it can be called by a larger application in the future.

### PR DESCRIPTION
**Pull request by alyxrossetti**
Closes #490 

@adamcee I just went ahead and made XML files since it wasn't much more difficult than creating text files

### CODE REVIEW

**Comment by adamcee** [comment]
@alyxrossetti Is the python code which generated the sitemaps checked into version control in the other repo? If not I would suggest checking it in to either this repo or the other one.

**Comment by adamcee** [comment]
@alyxrossetti This looks great overall :)

There is one thing I think we need to change. Please move both of the sitemap files and the sitemap index file directly into the `client/` directory and delete the `sitemap/` directory. My understanding is that this directory (unless we change our robots.txt) is where crawlers look for them, and that the sitemaps MUST be placed there in order to point to the book detail files. See: http://www.sitemaps.org/protocol.html#location -- basically a sitemap in `sitemap/` can only point to URL's which branch off of `sitemap/`

If you have already covered this ground and the current setup is OK then please just ignore ;)
@joshuago78 @jfranco-gri Once @alyxrossetti responds to above issue this branch should be good to merge and we should have our sitemap! 👍

**Comment by alyxrossetti** [comment]
@adamcee @joshuago78 I have not pushed the database or sitemap code to any repo because I'm not sure we have decided where they are going to fit in - they are currently located in a 3rd project directory locally (neither in funnel nor portal).  @joshuago78 Please let me know if you want me to push them somewhere...

**Comment by alyxrossetti** [comment]
@adamcee You are totally right about the above. Files have been moved - ready for merge!

**Comment by joshuago78** [comment]
Ideally the sitemap generation code would be in this repo and made into a Django command. We can do that in the next sprint.

**Pull request merged**
