### PR TITLE
Update/protractor version

### PR DESCRIPTION
**Pull request by joshuago78**

### CODE REVIEW

**Comment by alyxrossetti** [comment]
@joshuago78 I pulled this down and ran the two commands with sudo.  Chrome worked beautifully with all tests passing but Firefox still exits without running any tests.

**Comment by joshuago78** [comment]
OK, we can figure out the Firefox issue later

**Comment by alyxrossetti** [comment]
Okay - do you want me to merge and delete or do you want to do it?

**Comment by joshuago78** [comment]
I'm going to close this PR and submit another one to get rid of those redundant commits

**Pull request closed without merging**
