### PR TITLE
Bug/adv enter regression/369

### LINKED ISSUE #298: Don't use spaces in our CSS id's for facets
Makes it harder to get them with JQuery and does not follow standards.

http://stackoverflow.com/questions/596314/jquery-ids-with-spaces/596335#596335

Replace spaces with dashes or underscore.

### LINKED ISSUE #369: enable Enter button in Adv Search
The user should be able to simply hit the Enter key while performing an advanced search instead of having to click the button.

### PR DESCRIPTION
**Pull request by jfranco-gri**
Closes #369 
Closes #298 

It seemed there are two issues--the form element seemed to have some bad structure, probably due to a merge between my and Kristen's code.  And then after some internet searching, it seems you have to set buttons used as dropdown inside a form to have type="button". Otherwise, the 'enter' button will have strange results and won't submit the form.

Reviewers:

- [x] @joshuago78 
- [x] @adamcee 
- [x] @kristenGRI  -- Can you make sure that all your previous changes to this page still work?

### CODE REVIEW

**Comment by adamcee** [comment]
Looks good. Running e2e tests just to be safe expect they will pass.

**Comment by adamcee** [comment]
FYI I think the PR also closes issue #298 (Don't use spaces in our CSS id's for facets). 😸

**Comment by jfranco-gri** [comment]
Sweet!

**Comment by kristenGRI** [comment]
This looks good to me! Seems like all the stylings are still in place.

**Comment by joshuago78** [comment]
The flurry of PR merges this morning has created a few conflicts in this branch.

**Comment by jfranco-gri** [comment]
Fixed conflicts

**Pull request merged**
