### PR TITLE
Enhancement/split keywords unless quoted/626

### LINKED ISSUE #626: split keywords unless quoted
Users would like to be able to delete a single term from a keyword search. However, if multiple keywords were entered, they are grouped in the same search box chip. But sometimes users _do_ want terms grouped together, such as "New York". So,
- [ ] If a user puts a set of keywords in quotes, then keep them together in a single chip
- [ ] Otherwise, split all keyword terms into their own search box chips

### PR DESCRIPTION
**Pull request by susanley**
Closes #626.

### CODE REVIEW

**Comment by joshuago78** [comment]
This appears to work from the results page and from advanced search, but it does not work from the home page

**Comment by joshuago78** [comment]
This has a regression back to an old bug that we previously fixed. 

1. Start at home page and search for *New York* without quotes.
2. Click on *Home* in the menu.
3. Now search for *"New York"* with quotes.
4. Note that the old search parameters have persisted

Please fix the bug and write a test to ensure it remains squashed.

**Comment by susanley** [comment]
@joshuago78 Noted, will do.

**Comment by joshuago78** [comment]
OK, almost there. This branch has a couple small merge conflicts due to some other branches that were merged this morning.

**Comment by susanley** [comment]
@joshuago78 Merge conflicts resolved. :ok_hand:

**Pull request merged**
