### PR TITLE
Bug/misplaced pagination buttons/420

### PR DESCRIPTION
**Pull request by kristenGRI**
I would like to review this with the real data and see if the couple of fixes I put in place will work until I can figure out how to override the maxSize 5 set in dirPagination. 

Also included a fix to the misaligned "Clear All" Not sure why that keeps getting reintroduced. Filter Results should be an h4 tag but it keeps getting changed to an h6

### CODE REVIEW

**Comment by joshuago78** [comment]
OK, I put your branch on the dev instance: http://grpdev.getty.edu:8080

**Comment by joshuago78** [comment]
This looks better to me

**Comment by kristenGRI** [comment]
It's better unless you go the end in the medium display and then go one page back (so all next/last first/previous buttons appear) I was going to adjust the grid and some padding and I think I can get it to look good that way. It would be pretty quick to do. Thoughts?

**Comment by kristenGRI** [comment]
Just made a new commit and pushed the code up so you can see. You *should* be able to go to the last page with any sorting options or number of results per page and then click on the second to last page without breaking the grid when it;s in the med (992px) display.

**Comment by joshuago78** [comment]
Closes #420

**Comment by joshuago78** [comment]
When I test this out by shrinking the browser frame, there is still an awkward phase where the buttons are misaligned. So there are essentially 3 alignments
- Full screen - OK
- Middle size - Bad
- Small size - OK
- Tiny (mobile) - OK

**Pull request merged**
