### PR TITLE
Enhancement/style advanced search/403

### PR DESCRIPTION
**Pull request by kristenGRI**
Ready for review!

### CODE REVIEW

**Comment by kristenGRI** [comment]
@joshuago78 ready for review!

**Comment by jfranco-gri** [comment]
I noticed that hitting enter from a filter field input on the Advanced Search page no longer works.

**Comment by kristenGRI** [comment]
@jfranco-gri this doesn't seem to be working on http://grpdev.getty.edu/advanced either? Or at least not for me. Might be a separate issue?

**Comment by jfranco-gri** [comment]
@kristenGRI On Tuesday I pulled down the current develop branch and hitting enter from the filter inputs worked there.

**Pull request merged**
