### PR TITLE
Added spinner when executing searches

### LINKED ISSUE #482: Add throbber to display
Related to #480. 

We should add a throbber icon to the display after a filter or button has been selected in the results page. Currently, on a slow connection it appears that nothing happens.

### PR DESCRIPTION
**Pull request by jfranco-gri**
Closes #482 

Added spinner to display when making requests to django server. Added the angular-spinner module to our project, it seems to work pretty well for this. @kristenGRI you may want to take a look and see how it looks and/or change the styling. There's a .spinner class that controls the styling for it.

It's also possible to set a delay for the spinner so it only shows up on longer page loads. I didn't do this, but let me know if we want it.

### CODE REVIEW

**Comment by kristenGRI** [comment]
@jfranco-gri  I think the spinner looks fine for now. Might be neat to get a better looking one later but I think it does the job right now. I think adding a small delay might be nice? If only because it pops up briefly when you are adding filters/ keywords to the search and that appears to load fast enough not to need it.

**Comment by joshuago78** [comment]
This looks good to me. We can tweak the timing as needed.

But please add the spinner to the loading of the item detail pages, as that can have some lag time.

**Comment by adamcee** [comment]
FYI the spinner library used should be customizeable ;)

**Comment by adamcee** [comment]
FYI the spinner library used has a lot of visual customization http://spin.js.org/ :)

**Pull request merged**
