### PR TITLE
enhancement/old-portal-link/447

### PR DESCRIPTION
**Pull request by kristenGRI**
Ready for review! Noting that since we don't have the URL for the old portal site, the link currently goes nowhere.

### CODE REVIEW

**Comment by joshuago78** [comment]
I thought you were going to use the other design

**Comment by joshuago78** [comment]
Before you redo this, though, I should ask Annie which one she prefers.

**Comment by kristenGRI** [comment]
Oh, I think there was confusion on my part because of the images posted in a different order than what I had labeled them (v1 and v2) So I thought you were talking about v2 not the second image in the issue. After we see what they say, I will make the change if needed! Sorry about that!

**Comment by kristenGRI** [comment]
Ready for review!

**Pull request merged**
