### PR TITLE
Bug/mobile css issues/519

### LINKED ISSUE #519: Mobile CSS issues
I have catalogued a number of CSS issues on mobile that I will use this ticket to address them.

- [x] Clear all button on facet sidebar opens and closes the facets

- [x] Dropdown on recent searches page flows out of the container

- [x] My Records and Recent Searches tabs wrap (Saved Records page)

- [x] Dropdown arrow missing from Explore Getty menu

- [x] Search Icon is misaligned on homepage

- [x] reduce padding on all containers

- [x] sort by and show filter dropdown need adjusting so sort by text doesn't flow out of the container when "newly added first" is selected

### PR DESCRIPTION
**Pull request by kristenGRI**
Ready for review. Had to rearrange and change some stuff in the search-results.html file to address some of the issues we were having.  Closes #519

### CODE REVIEW

**Comment by joshuago78** [comment]
I have deployed this to http://portalbeta.getty.edu for testing.

The new code seems to work on desktop, but I get no searchbox on my phone or tablet

**Comment by joshuago78** [comment]
Disregard the last comment. The searchbox does appear on the home page now. It appears to be spotty though. Obviously not a CSS problem.

**Comment by joshuago78** [comment]
There are several protractor tests now failing because of a missing toggle sort button:

```bash
Failed: No element found using locator: By.id("toggle-sort-btn")
```

**Comment by kristenGRI** [comment]
Added back the missing ID. Ready for review.

**Pull request merged**
