### PR TITLE
Enhancement/add html description tags/701

### LINKED ISSUE #701: Add HTML description tags
- Add a `meta` tag with attribute `name="description"` to the `head` element of every item page.
  - the `content` attribute should contain a string with the following format: 

><date issued (if one exists)>, <first creator (if any exist)> <first contributor (if no creators exist)>: <description field (repeat for each one)>

- Add a `meta` tag to the home page as well with the following `content`: 

>The Getty Research Portal™ is a free online search platform providing worldwide access to an extensive collection of digitized art history texts from a range of institutions. This multilingual and multicultural union catalog affords art historians and other researchers the ability to search and download complete digital copies of publications devoted to art, architecture, material culture, and related fields.

### PR DESCRIPTION
**Pull request by susanley**
Closes #701.

### CODE REVIEW

**Comment by joshuago78** [comment]
This is not working on my local instance. Not sure why not.

Also, I found a bug where the code has an error if the book does not have `description` metadata: see line 56 in `book-detail.controller.js`.  All metadata elements should be considered optional, and therefore code should defensively retrieve elements from it.

**Comment by susanley** [comment]
@joshuago78 Noted, will address. Are all the tests for description failing? When you say not working, what specifically is not working?

**Comment by joshuago78** [comment]
I did not run the tests. I just went to a book detail page and viewed the source: no meta tags.

**Comment by susanley** [comment]
@joshuago78 alrighty, will take a look

**Pull request merged**
