### PR TITLE
Bug/facet ampersand/535

### LINKED ISSUE #535: faceting bug
1. go to http://portalbeta.getty.edu
2. search for "painting"
3. Observe the "M. Knoedler & Co." facet in the Creator/Contributor facet category says it will narrow your results 311 hits
4. click on that facet
5. observe that you get 0 results instead

### PR DESCRIPTION
**Pull request by jfranco-gri**
Closes #535

### CODE REVIEW

**Comment by joshuago78** [comment]
The test is failing on my machine

**Comment by joshuago78** [comment]
I have also deployed it to portalbeta to make sure it was not my machine causing the problem. The bug persists there as well.

**Comment by jfranco-gri** [comment]
which test is failing? I added an E2E test and a django test. What is the output of the failing test?

**Comment by joshuago78** [comment]
The E2E test is failing.

**Comment by joshuago78** [comment]
```
Failures:
1) Search Results should work when facets have ampersands in them
  Message:
    Expected 0 to equal 1.
  Stack:
    Error: Failed expectation
        at /home/jgomez/projects/portal/test/e2e/search-results.e2e.spec.js:236:20
        at process._tickCallback (node.js:401:9)
```

**Pull request merged**
